### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by ruixilin** [pasinit/sensembert_downloads#1]
I read your paper SENSEMBERT: Context-Enhanced Sense Embeddings
for Multilingual Word Sense Disambiguation in AAAI2020, and I admire your work in learning sense embeddings. May I know if there is a plan of releasing source code (model, training, and etc.) please? I really look forward to learning more about your methods through the code. Thank you!

**Comment by pasinit** [comment]
Hi, thank you very much for your interest. At the moment we are not planning to release the code at any time soon. In any case please refer to our official website http://sensembert.org/ which contains the latest version of the embeddings and will, in case, contain news about their future development. 
Cheers, Tommaso

**Comment by Hadjerkhd** [comment]
Hello, thanks  for the shared SensEmBERT embeddings. I would to know in which format these embedding were stored ? FastText format ? Thank you !
