### ISSUE TITLE
Sensembert Website down?

### ISSUE THREAD

**Issue by kanishkamisra** [pasinit/sensembert_downloads#3]
Hey! I wanted to explore the ares and sensembert embeddings but I am unable to access the website. Is it down?

**Comment by pasinit** [comment]
Hi, thanks for your interest. We moved some machines and we are now figuring out why some of the websites are offline. I will inform you as soon as they will back up. Sorry for this inconvenience.

**Comment by kanishkamisra** [comment]
No problem, thanks! Is it fine to leave this issue open until the website is back up?

**Comment by pasinit** [comment]
Hi, the website should be now reachable at sensembert.org! Let me know if there is any other issue!

Have a nice day and sorry again for the inconvenience.

**Comment by kanishkamisra** [comment]
No worries -- thanks for fixing it!!
